import { AGCLogo } from '../shared/AGCLogo';
import { MODULES } from '../../data/modules';

/**
 * A highly condensed, print-optimized One-Page Strategic Plan view.
 * It gracefully handles missing data.
 */
export function OnePagePlan({ data }) {
  const companyName = data?.user?.name || "Company";

  const getAnswers = (moduleId) => data?.modules?.[moduleId]?.data || {};

  const mission = getAnswers('mission');
  const vision = getAnswers('vision');
  const strategy = getAnswers('strategy');
  const framework = getAnswers('framework');

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{ maxWidth: 1000, margin: '0 auto', background: 'var(--panel)', padding: '40px', borderRadius: 16 }}>
      {/* ─── Web Header Controls (Hidden during print) ─── */}
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <div>
          <h2 style={{ fontSize: 24, margin: 0, color: 'var(--ink)' }}>One-Page Strategic Plan</h2>
          <p style={{ color: 'var(--muted)', margin: '4px 0 0 0', fontSize: 13 }}>Standardized V/T/O layout for printing.</p>
        </div>
        <button className="gold-btn" onClick={handlePrint} style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="6 9 6 2 18 2 18 9"/>
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/>
            <rect width="12" height="8" x="6" y="14"/>
          </svg>
          Print PDF
        </button>
      </div>

      <div className="gold-rule no-print" style={{ marginBottom: 40 }} />

      {/* ─── Printable Document ─── */}
      <div id="opsp-doc">
        {/* Document Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid var(--ink)', paddingBottom: 16, marginBottom: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ filter: 'grayscale(100%) brightness(0)' }} className="print-only">
              <AGCLogo size={42} />
            </div>
            <div className="no-print"><AGCLogo size={42} /></div>
            <div>
              <h1 style={{ margin: 0, fontSize: 28, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--ink)' }}>{companyName}</h1>
              <p style={{ margin: 0, fontSize: 12, fontWeight: 'bold', color: 'var(--muted)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Strategic Plan</p>
            </div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ margin: 0, fontSize: 12, color: 'var(--muted)' }}>Generated by <br/><strong>Business Architect</strong></p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gap: 32 }}>
          
          {/* LEFT COLUMN: Foundation (Mission & Vision) */}
          <div>
            {/* Core Focus / Mission */}
            <div className="dash-card" style={{ padding: '20px', marginBottom: 24 }}>
              <h3 style={{ margin: '0 0 16px 0', fontSize: 18, borderBottom: '1px solid var(--border)', paddingBottom: 8, color: 'var(--ink)' }}>1. Core Focus (Mission)</h3>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Purpose / Why We Exist</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{mission.purpose || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Our Promise</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{mission.promise || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Who We Serve</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{mission.people || '—'}</p>
              </div>
            </div>

            {/* 3-Year Picture (Vision) */}
            <div className="dash-card" style={{ padding: '20px' }}>
              <h3 style={{ margin: '0 0 16px 0', fontSize: 18, borderBottom: '1px solid var(--border)', paddingBottom: 8, color: 'var(--ink)' }}>2. Future Picture (3-5 Years)</h3>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Target Goal</strong>
                <p style={{ fontSize: 16, fontWeight: 'bold', margin: '4px 0 0 0', color: 'var(--ink)' }}>{vision.big_goal || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>What It Looks Like</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{vision.future_state || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Market Position</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{vision.market_position || '—'}</p>
              </div>
            </div>
          </div>

          {/* RIGHT COLUMN: Execution (Strategy & Framework) */}
          <div>
            {/* Strategy / 1-Year Plan */}
            <div className="dash-card" style={{ padding: '20px', marginBottom: 24 }}>
              <h3 style={{ margin: '0 0 16px 0', fontSize: 18, borderBottom: '1px solid var(--border)', paddingBottom: 8, color: 'var(--ink)' }}>3. Strategic Plan (1-Year Focus)</h3>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Strategic Anchors</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{strategy.strategic_anchors || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Top 3 Priorities</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{strategy.priorities || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Competitive Advantage</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{strategy.advantage || '—'}</p>
              </div>
            </div>

            {/* Scoreboard / Execution */}
            <div className="dash-card" style={{ padding: '20px' }}>
              <h3 style={{ margin: '0 0 16px 0', fontSize: 18, borderBottom: '1px solid var(--border)', paddingBottom: 8, color: 'var(--ink)' }}>4. Leadership Scoreboard</h3>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>The 3-5 Key Metrics</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{framework.scoreboard || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Meeting Rhythm</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{framework.meeting_rhythm || '—'}</p>
              </div>
              <div style={{ marginBottom: 12 }}>
                <strong style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--muted)', display: 'block' }}>Execution Tracking</strong>
                <p style={{ fontSize: 14, margin: '4px 0 0 0', color: 'var(--ink)' }}>{framework.commitments || '—'}</p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
